// <auto-generated />
<<<<<<< HEAD
using System;
=======
>>>>>>> 5b990030e76124dbdc472c9728fc1284ec006a36
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using phanhuynhtrongtin_2122110382.Data;

#nullable disable

namespace phanhuynhtrongtin_2122110382.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

<<<<<<< HEAD
            modelBuilder.Entity("phanhuynhtrongtin_2122110382.Controllers.OrderDetail", b =>
                {
                    b.Property<int>("OrderDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderDetailId"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("OrderDetailId");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("phanhuynhtrongtin_2122110382.Model.Category", b =>
                {
                    b.Property<int>("Cat_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Cat_Id"));

                    b.Property<string>("Cat_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Cat_Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("phanhuynhtrongtin_2122110382.Model.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("OrderId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("phanhuynhtrongtin_2122110382.Model.Product", b =>
                {
                    b.Property<int>("Product_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Product_Id"));

                    b.Property<int>("Cat_Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("Create_at")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Delete_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<string>("Product_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Update_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Product_Id");

                    b.HasIndex("Cat_Id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("phanhuynhtrongtin_2122110382.Model.User", b =>
                {
=======
            modelBuilder.Entity("phanhuynhtrongtin_2122110382.Model.Category", b =>
                {
>>>>>>> 5b990030e76124dbdc472c9728fc1284ec006a36
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

<<<<<<< HEAD
                    b.Property<string>("Email")
=======
                    b.Property<string>("Image")
>>>>>>> 5b990030e76124dbdc472c9728fc1284ec006a36
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

<<<<<<< HEAD
                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
=======
                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("phanhuynhtrongtin_2122110382.Model.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Price")
>>>>>>> 5b990030e76124dbdc472c9728fc1284ec006a36
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

<<<<<<< HEAD
                    b.ToTable("Users");
                });

            modelBuilder.Entity("phanhuynhtrongtin_2122110382.Controllers.OrderDetail", b =>
                {
                    b.HasOne("phanhuynhtrongtin_2122110382.Model.Order", "Order")
                        .WithOne("Detail")
                        .HasForeignKey("phanhuynhtrongtin_2122110382.Controllers.OrderDetail", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("phanhuynhtrongtin_2122110382.Model.Order", b =>
                {
                    b.HasOne("phanhuynhtrongtin_2122110382.Model.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("phanhuynhtrongtin_2122110382.Model.Product", b =>
                {
                    b.HasOne("phanhuynhtrongtin_2122110382.Model.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("Cat_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("phanhuynhtrongtin_2122110382.Model.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("phanhuynhtrongtin_2122110382.Model.Order", b =>
                {
                    b.Navigation("Detail")
                        .IsRequired();
                });

            modelBuilder.Entity("phanhuynhtrongtin_2122110382.Model.User", b =>
                {
                    b.Navigation("Orders");
=======
                    b.ToTable("Products");
>>>>>>> 5b990030e76124dbdc472c9728fc1284ec006a36
                });
#pragma warning restore 612, 618
        }
    }
}
